### ISSUE TITLE
Add colored text capability for windows

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#13]
See `inspect.common.fmtStr`:

Currently the function only supports colors for linux systems supporting ASCII-color-escape-codes. For the readability of test output it would be wise to also support colored text under windows.

No idea yet though on how to implement this. Do you?

**Comment by JanKirchhofTU** [comment]
Google comes up with this suggestion (among others):

**Comment by ChristophWWagner** [comment]
Looks promising. Needs to be considered during print output though. Then maybe the best solution is encapsulating terminal output potentially containing colors. The scope of this should be the test output only as it generates colored strings that get printed at a later stage.

**Comment by ChristophWWagner** [comment]
won't fix.

Too much hassle to rework this to a platform-independent solution that supports colors on terminals that don't want to play nice with anyone.

![image](https://user-images.githubusercontent.com/23030662/48418406-7ff81000-e755-11e8-8261-3f08b474e4aa.png)

Reopen this if either util/bee.py or windows changed significantly.
