### ISSUE TITLE
Move documentation to Sphinx

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#17]
## Sphinx
Sphinx is a configurable parser of python source code, which can automatically extract docstrings from modules, submodules and so forth. It generates *.rst-files, which then can be built into html or LaTeX for deployment.

## Goals

1. Get rid of the cancerous appendices to the current fastmat-classes which forms the documentation and incorporate this content into the class documentation itself
2. Add docstrings, which are readable via help() from the python shell to every module, submodule and avaiable function in fastmat
3. Include and show performance plots for each class in its respective documentation
4. Automatic deployment of the documentation to fastmat.readthedocs.io

## Resources

- https://pypi.python.org/pypi/numpydoc?
- https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
- https://www.python.org/dev/peps/pep-0257/
- https://www.python.org/dev/peps/pep-0256/
- https://www.python.org/dev/peps/pep-0258/

**Comment by SebastianSemper** [comment]
The only thing missing here are the performance plots. Any ideas on that, @ChristophWWagner ?

**Comment by ChristophWWagner** [comment]
do you have a workflow in mind what needs to be done to achieve what result?

btw: is updating readthedocs.io actually in the CI build yet?

**Comment by SebastianSemper** [comment]
regarding the btw: dunno. :-/

I noticed, that the`make doc` target still points to our old makefile. We should replace this with the new sphinx command.

Concerning the performance plots, we only need to write a routine that takes a csv-file generated by the benchmakrs and then makes a nice plot (possibly containing several subplots), which is saved to 'doc/_static' by default or somewhere else if specified.

**Comment by SebastianSemper** [comment]
Closing and opening new issue for plot generation.
