### ISSUE TITLE
Remove matplotlib from the package dependencies

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#2]
Thanks to the addition of travis CI from @mp4096 an package dependency issue was found:

As matplotlib is only used for plotting in some demos and the bee-utility it is not an actual requirement of the package. Suggesting the replacement of `import matplotlib` by:
```
try:
    import matplotlib
except ImportError:
    raise ImportError("matplotlib is not installed but plotting was requested.")
```
Any comments on this?

**Comment by mp4096** [comment]
If `matplotlib` is not required for testing, I can adjust my PR and don't install `matplotlib` during CI. This is actually quite prudent as it reduces load on Travis.

BTW, pro tip: You can [specify language after the backticks to get syntax highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting):
```python
try:
    import matplotlib
except ImportError:
    raise ImportError("matplotlib is not installed but plotting was requested.")
```

**Comment by mp4096** [comment]
In general, I would strongly argument for dropping Python 3.3 support. [It reaches end of life in September 2017.](https://www.python.org/dev/peps/pep-0398/#lifespan)

Also you might want to see the Python 3 statement: http://www.python3statement.org/

**Comment by ChristophWWagner** [comment]
Thanks for your hint. In fact I was thinking about extending CI coverage to older python version as we experienced some applications relying on ancient software (python 2.6) but we did not yet wanted to open the full rabbithole of backwards compatibility although it should be achievable with just minor modifications.

**Comment by mp4096** [comment]
Oh, I see. 2.6 is the oldest version Travis supports: https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against

**Comment by ChristophWWagner** [comment]
We also stumbled across some packages (xarray), that we would love to support but do not want to actually open up a dependency. Maybe it is possible to introduce playing "see if it's available and if it is, enable the feature dynamically" with matplotlib first, and then allow adding more and more

**Comment by ChristophWWagner** [comment]
just as a note: as we rely on randomly chosen test examples we get a convergance measure which itself is stochastic. Thus we declare a quite close limit to detect failure which occasionally happen for actually problem-free classes. Partial is a candidate that has a quite narrow limit and thus failes from time to time. If you could, would it be possible to allow rerunning failed Travis-CI tests when they completed with such a failure?

**Comment by ChristophWWagner** [comment]
matplotlib removed as dependency in current master. Partial test robustness improved as well.
