### ISSUE TITLE
Partial sanity check on index type required

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#25]
Partial should complain during `__init__()` if indexing arrays of non-integer data type are passed.

**Comment by SebastianSemper** [comment]
Was this included in 0.1.2.?

**Comment by ChristophWWagner** [comment]
Yes, this was resolved in 22b2e8b3af8e33f7e9ac1782005817db4b059f92. Indexing Partial matrices with boolean arrays is now supported.
