### ISSUE TITLE
fastmat and Spyder's  "User Module Reloader"

### ISSUE THREAD

**Issue by JanKirchhofTU** [EMS-TU-Ilmenau/fastmat#27]
When I do something like

```python
import fastmat as fm
HadamardMatrix = fm.Hadamard(10)
```

and run this in an IPython console, it will run smoothly the first time. Starting from the second execution (in the same console), I get

```python
  File "/path/.local/lib/python2.7/site-packages/fastmat/core/calibration.py", line 68, in getMatrixCalibration
    return calData.get(target, None)

AttributeError: 'NoneType' object has no attribute 'get'
```
each time fastmat is used in the code. 

fastmat seems to have problems with Spyder's [**User Module Reloader (UMR)** feature](https://pythonhosted.org/spyder/ipythonconsole.html) causing the warnings. Simply excluding it from the UMR works so far.

**Comment by JanKirchhofTU** [comment]
Moving on further, this issue exists only in spyder-versions based on python 2.x but not in spyder connected with python 3.x.

**Comment by ChristophWWagner** [comment]
Does the issue occur after class calibration, too?

Please create a calibration data set with
```
python util/bee.py calibrate all -o cal.json
```

and then use that calibrated file in your fastmat session:
```python
from fastmat import *
fastmat.core.calibration.loadCalibration('cal.json')
```

**Comment by SebastianSemper** [comment]
Is this fixed?

**Comment by ChristophWWagner** [comment]
I would assume this to be a `yes`. closing.

https://github.com/spyder-ide/spyder/pull/7198/commits/26fe99ff2b11c77f5bb3c105e008891f53a09aef
