### ISSUE TITLE
Use numpy svd as fallback, if power iteration to compute the largest singular value fails

### ISSUE THREAD

**Issue by JanKirchhofTU** [EMS-TU-Ilmenau/fastmat#33]
### Problem
The power iteration to compute the largest Singular Value sometimes fails, if the matrix is badly conditioned leading to two "largest" singular values that have approximately the same value.

### Enhancement/Discussion
We could think about using numpy.linalg.svd in that case as a fallback. Obviously, this is not a proper solution for large(r) problem sizes.

**Comment by SebastianSemper** [comment]
I will incorporate the following:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html
as soon was we have the scipyLinearOperator stuff in place.

**Comment by SebastianSemper** [comment]
Done in #43 and #60 . closing.
