### ISSUE TITLE
Bug in Fourier: wrong complexity estimates

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#37]
When Fourier optimization decides to apply Bluestein's method the class instance incorrectly reports the complexity estimate for the (apparently worse conditioned) baseline fourier order. For larger sizes this can lead to the undesired effect, that a dense matrix multiplication is enforced (which should not be neccessary). Also, there is a mismatch in complexity estimate and actual computation, which is reflected in bad calibration estimates.

Suggested fix: Add a complexity estimation for the actual FFT complexity.

**Comment by SebastianSemper** [comment]
Resolved with #39 – closing.
