### ISSUE TITLE
Extension and Renaming of largestSV and largestEV

### ISSUE THREAD

**Issue by SebastianSemper** [EMS-TU-Ilmenau/fastmat#43]
1. We should rename the existing properties to largest{Singular,Eigen}Value, since {S,E}V could mean bot singular vector or singular value.

2. We also calculate the {singular,eigen} vectors and cache these like we do with the values already. This poses no additional computational overhead, since during the calculations of the {singular,eigen} values, these vectors are generated anyway.

**Comment by ChristophWWagner** [comment]
good point. Remember to also update the demos. There might be some reference in there as well

**Comment by SebastianSemper** [comment]
How about the following: 

If the user accesses largest{Singular,Eigen}Value, we do not cache the associated vectors. If on the other hand, the user accesses largest{Singular,Eigen}Vector, we automatically cache the corresponding {singular,eigen} value. 

In case the user first accessed largest{Singular, Eigen}Value and _then_ also wants to access the vectors, we can start the iterations by warmstarting them with the already cached {singular,eigen}vectors, thus speeding things up tremendously. Of course, we then cache the calculated vectors.

**Comment by SebastianSemper** [comment]
Resolved and implemented by  #60
