### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#46]
As github suggests it would be a very nice thing to introduce contribution guidelines and a code of conduct to (1) welcome new users to participate in the project and (2) to define some rough rules for living and extending fastmat.

Do you have suggestions on a particular guideline, what you want to see or what you don't?

Code of Conduct template:
https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md

Example guideline:
https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

I'd like to suggest creating example documents in a separate branch and have contributions collected there. Please feel free to propose other ideas on how to proceed

**Comment by ChristophWWagner** [comment]
As I found out we have some! In the wiki! We have a wiki!

We should move the contribution guidelines from the wiki to the codebase as `CONTRIBUTING.md`. If it's there it's visibility is much better.

**Comment by SebastianSemper** [comment]
Implemented in recent merge at #6e528dee9ad7cdc0e9f9bd1. Closing.
