### ISSUE TITLE
Feature proposal: slicing of matrices in element access

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#5]
Include the functionality of the `Partial()` class into `Matrix.__getitem__`

Basically a submatrix may be returned by passing slices with __getitem__():

intended usage examples:
```python
>>> F = Fourier(4)
>>> F[1,1]
(0. -1.j)
>>> F[:, [2,3]]
<Partial[4x2](Fourier[4x4]):0x1234567ABCD>
>>> F[:2, 2:]
<Partial[2x2](Fourier[4x4]):0x1234567BCDE>
>>> F[:2, 2:].array
array([[ 1.+0.j,  1.+0.j],
        -1.+0.j,  0.+1.j]])
```

**Comment by SebastianSemper** [comment]
Several things could be considered here. First, which Features of numpy indexing do we include? Second, what about nested Partials?

**Comment by ChristophWWagner** [comment]
Numpy itself implements slicing via the standard python __getitem__ attribute. We could stick to the currently supported cased:

 * assume a tuple of two ints and return the element at that position

and extend this interface with the following cases:

 * an `Ellipsis` object itself returns `matrix.array`. This covers the following case:
    ```python
    >>> matrix[...] # = matrix._getArray()
    ```
 * a two-dimensional tuple with both elements being either an int, a list, a tuple, a `slice` object or `Ellipsis`. These map to the following cases:
    ```python
    >>> matrix[1, 2] # matrix._getItem(1, 2)
    >>> matrix[1, :] # matrix._getRow(1)
    >>> matrix[:, 2] # matrix._getCol(2 )
    >>> matrix[:, :] or matrix[:, ...] or matrix[..., :] # matrix._getArray()
    >>> matrix[:, 1:3] or matrix[:, (1, 4)] or matrix[:, [1,4]] # matrix._getRows(2nd argument evaluated)
    >>> matrix[1:3, :] or matrix[(1,4), :] or matrix[:, [1,4]] # matrix._getCols(1st argument evaluated)
    ```
 * all other cases shall be errored

**Comment by ChristophWWagner** [comment]
I would not recommend returning Partials of matrices through this interface as I would assume one expects to access an element or one to many columns / rows, served as a ndarray.

Anyhow, Partials could inherit the same interface easily! Just imagine this way of casting them:
```python
>>> mat = fastmat.Matrix(...)
>>> Partial(mat, 1:3, :)
>>> Partial(mat, ...)
>>> Partial(mat, :5, :)
```
The existing interface specifying explicit indexing arrays for `N` and `M` does not need to be removed. Both interfacing variants could exist in parallel in evaluating `Partial.__init__()` in a way like this:
    ```python
    def __init__(self, matrix, *args, **kwargs)
        N = kwargs.get('N', None)
        M = kwargs.get('M', None)
        if len(args) == 2 and N is None and M is None:
            # proposed interface
        elif len(args) == 0 and (N is not None or M is not None):
            # current interface
        else:
            raise ValueError("Partial: Unsupported arguments")
    ```

**Comment by ChristophWWagner** [comment]
Using ellipses or slice notation outside of __getitem__ was found to be currently not possible. Therefore no slicing interface will be added to Partial.
