### ISSUE TITLE
Demos unhappy. Demos sad. And without documentation.

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#68]
Somewhere along the tracks of milestone 0.2 implementation something seems to have happened to let the demos frown. Let's find out what they dislike and make them great again! We just need to find a way to convince them.

And if we're at it... add a page of documentation for each of them.

**Comment by SebastianSemper** [comment]
We will reopen the discussion about demos somewhere down the road in a broader sense. closing for now.
