### ISSUE TITLE
STELA can't handle complex valued inputs

### ISSUE THREAD

**Issue by JanKirchhofTU** [EMS-TU-Ilmenau/fastmat#76]
STELA seems to have problems handling complex values. For example,
running the *cs_example* in the  example section of the documentation (cf. commit d513a8d2bfa381cb69acff328eab1bd92d7e7104)
leads to the following warning:
```
/STELA.py:238: ComplexWarning: Casting complex values to real discards the imaginary part                                                                                                                                  
  0
```
and the reconstruction is then useless.

**Comment by JanKirchhofTU** [comment]
Is this solved with b22d18fc385db32d85ba1b24f09991f8d06d110a? @SebastianSemper?

**Comment by SebastianSemper** [comment]
Don't think so.

JanKirchhofTU <notifications@github.com> schrieb am Fr., 24. Apr. 2020,
17:11:

**Comment by JanKirchhofTU** [comment]
The added conj() in [Line 219](https://github.com/EMS-TU-Ilmenau/fastmat/commit/b22d18fc385db32d85ba1b24f09991f8d06d110a#diff-5f55d1dbd644cdc7538a986ccb5e4ef9R219) indicates the opposite and a quick test gave correct results with complex valued inputs. Closing.
