### ISSUE TITLE
Error with running demos: compOmpIsta, lowRankApprox and sparseReco

### ISSUE THREAD

**Issue by ahmadomira** [EMS-TU-Ilmenau/fastmat#90]
Trying to run any of the demos directly from default fastmat directory (fastmat/demo) does't work and results following error: 

```
File "~/git/fastmat/fastmat/__init__.py", line 62, in <module>
    from .Matrix import Matrix, Hermitian, Conjugate, Transpose, flags
ModuleNotFoundError: No module named 'fastmat.Matrix'
```

But copying the demos to an independent directory and running `compOmpIsta`, `lowRankApprox` or `sparseReco` gives: 

```
File "~/fastmat_demo/compOmpIsta.py", line 111, in <module>
    fastmat.algorithms.OMP, mat, b, K)
AttributeError: module 'fastmat' has no attribute 'algorithms'
```

OS: MacOS Big Sur version 11.0.1
Python: v3.8.6
C-compiler: Clang 6.0 (clang-600.0.57)

**Comment by SebastianSemper** [comment]
How did you install fastmat?

**Comment by ahmadomira** [comment]
> How did you install fastmat?
> […](#)

pip install fastmat

**Comment by SebastianSemper** [comment]
so you cloned the demos from git and then installed fastmat from pypi and
then ran the demos from the git-repository?

**Comment by ahmadomira** [comment]
> so you cloned the demos from git and then installed fastmat from pypi and then ran the demos from the git-repository?
> […](#)

The other way around, meaning: pip installed fastmat -> cloned the fastmat repo -> ran the demo directly from the git-repository (-> and later on form a separate directory, as described)

**Comment by ChristophWWagner** [comment]
Please check if this is related to #88 and if the suggestions of https://github.com/EMS-TU-Ilmenau/fastmat/issues/88#issuecomment-778697597 might apply here, too

**Comment by ChristophWWagner** [comment]
The problem could not be reproduced successfully with the given information. Seems like a problem with importing the package in your local configuration.

Closing the issue for now.

Feel free to reopen if there is new information
